export const SUPER_ADMIN_EMAIL = 'PUT_YOUR_SUPER_ADMIN_EMAIL_HERE';

export const LOCAL_ADMIN_EMAIL = 'PUT_YOUR_LOCAL_ADMIN_EMAIL_HERE';
export const LOCAL_ADMIN_LOGIN = 'PUT_YOUR_LOCAL_ADMIN_LOGIN_HERE';
export const LOCAL_ADMIN_PASSWORD = 'PUT_YOUR_LOCAL_ADMIN_PASSWORD_HERE';

export const FIREBASE_CONFIG = {
  apiKey: 'PUT_YOUR_FIREBASE_API_KEY_HERE',
  authDomain: 'PUT_YOUR_PROJECT_ID.firebaseapp.com',
  projectId: 'PUT_YOUR_PROJECT_ID',
  appId: 'PUT_YOUR_FIREBASE_APP_ID_HERE',
};
